### ISSUE TITLE
没产出对应的报告文件

### ISSUE THREAD

**Issue by wooyin** [c0ny1/java-object-searcher#2]
测试环境：sample-shiro-web-1.2.0 + tomcat 7.0.79 + Java SDK 1.7.0_80

断点位置
![image](https://user-images.githubusercontent.com/48854942/81365836-ca283a80-911b-11ea-8cc2-9877ca9aba0a.png)

Evaluate报错
![image](https://user-images.githubusercontent.com/48854942/81365853-dad8b080-911b-11ea-818a-851ef6629558.png)

**Comment by c0ny1** [comment]
`ClassNotFound`说明部署到tomcat下的war里没有java-objcet-searcher.jar

**Comment by wooyin** [comment]
测试环境：sample-shiro-web-1.2.0 + tomcat 7.0.79 + Java SDK 1.7.0_80

没找到大佬的Thread的链，实际用ysoserial打也没打成功，不知道是不是我姿势对不对
![image](https://user-images.githubusercontent.com/48854942/81390632-610dea80-914e-11ea-884f-74679710889c.png)

![image](https://user-images.githubusercontent.com/48854942/81390639-64a17180-914e-11ea-8125-2388c942b884.png)

改用 tomcat 8.0.30，报错
￼
![image](https://user-images.githubusercontent.com/48854942/81390856-bc3fdd00-914e-11ea-80b3-b09520c60266.png)

**Comment by c0ny1** [comment]
请用最新版本
