### ISSUE TITLE
!visited.contains(filed_object) 建议增加 try...catch

### ISSUE THREAD

**Issue by feihong-cs** [c0ny1/java-object-searcher#4]
用 Jetty 9.4.30 v20200611 测试的时候发现这里有空指针异常，发现原来在调用 hashCode 的时候有可能抛空指针异常，导致程序无法继续运行
https://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
![image](https://user-images.githubusercontent.com/59082458/87134875-db342a00-c2cb-11ea-8c56-a017a2980efc.png)

**Comment by c0ny1** [comment]
已临时采用捕捉异常解决（ 3aedbbf941d1c4bf6c63c0d1f08b8c82837bf24f ），但也引入新问题：HttpFields等类型的Object无法搜索，正寻找新的解决方案。
