### ISSUE TITLE
Keyword list无法找到，是因为tomcat和jdk 原因么

### ISSUE THREAD

**Issue by yaoxiaodai** [c0ny1/java-object-searcher#5]
![image](https://user-images.githubusercontent.com/28942595/132643036-90ee8449-5f79-48c7-a93a-fae8b9f43e08.png)

**Comment by c0ny1** [comment]
如果项目已经加入java-object-searcher.jar到lib,那Evaluate 快捷键`option + 回车`(macOS)引入下就行。

**Comment by yaoxiaodai** [comment]
已解决，还以为会自动调用java-object-searcher.jar
